[package]
name = "unmemftp"
version = "0.1.0"
authors = ["Julius Michaelis <gitter@liftm.de>"]
edition = "2018"

[dependencies]
libunftp = "0.11.0"
tokio = { version = "0.2.21", features = ["full"] }
async-trait = "0.1.31"

[dev-dependencies]
ftp = "3.0.1" # Ugh, old datetime…
