[package]
name = "ftp2mfs"
version = "0.1.0"
authors = ["Julius Michaelis <gitter@liftm.de>"]
edition = "2018"

[dependencies]
#ftp = "3.0.1" # Rust rots amazingly fast
ftp = { git = "https://github.com/wnklmnn/rust-ftp.git", rev = "0a122e412509a5a4b2990edbcfd926ce485a1e52" } # branch = "updateDeps"
clap = "3.0.0-beta.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
pathdiff = "0.2.0"
tokio = { version = "0.2.21", features = ["macros"] }
crossbeam-channel = "0.4.2"
humantime = "2.0.0"
anyhow = "1.0"
hostname = "0.3"
nanoid = "0.3"
ignore = "0.4"
serde_yaml = "0.8"
url_serde = "0.2"
url = "1"
serde-humantime = "0.1.1"
blake3 = "0.3"
mfs = { path = "crates/mfs" }

[dev-dependencies]
libunftp = "0.11.0"
tokio = { version = "0.2.21", features = ["full", "macros"] }
async-trait = "0.1.31"
unmemftp = { path = "crates/unmemftp" }

[workspace]
members = [
	"crates/unmemftp",
	"crates/mfs",
]
