[package]
name = "ftp2mfs"
version = "0.1.0"
authors = ["Julius Michaelis <gitter@liftm.de>"]
edition = "2018"

[dependencies]

# Only here because of the MFS shim
bytes = "0.5.4"
futures-core = "0.3.5"
futures-util = "0.3.5"

#ftp = "3.0.1" # Rust rots amazingly fast
ftp = { git = "https://github.com/wnklmnn/rust-ftp.git", rev = "0a122e412509a5a4b2990edbcfd926ce485a1e52" } # branch = "updateDeps"
clap = "3.0.0-beta.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
pathdiff = "0.2.0"
ipfs-api = "0.7.2"
tokio = { version = "0.2.21", features = ["macros"] }
crossbeam-channel = "0.4.2"
humantime = "2.0.0"
anyhow = "1.0"
failure = "0.1.8" # ipfs-api leaking "implementation details"… -.-
futures = "0.3.5" # likewise, from ipfs
hostname = "0.3"
nanoid = "0.3"
ignore = "0.4"
serde_yaml = "0.8"
url_serde = "0.2"
url = "1"
serde-humantime = "0.1.1"

[dev-dependencies]
libunftp = "0.11.0"
tokio = { version = "0.2.21", features = ["full", "macros"] }
async-trait = "0.1.31"
unmemftp = { git = "https://github.com/jcaesar/unmemftp.git", rev = "adc2c276790864cd0887212c62da81b8ac88c0db" } # = { "path" = "../unmemftp" }
